version: '2'
services:
    node-cli:
        image: node:5
        env_file: .env
        entrypoint: bash
        working_dir: /app
        ports:
            - "8082:8082"
        volumes:
            - .:/app
    watch:
        image: node:5
        env_file: .env
        entrypoint: npm run watch
        working_dir: /app
        ports:
            - "8082:8082"
        volumes:
            - .:/app
    redis:
        image: redis:3
        ports:
          - "6379:6379"
    kue:
        image: node:5
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: node_modules/kue/bin/kue-dashboard -p 3050 -r redis://docker.local:6379
        ports:
          - "3050:3050"
